def serialize_report(rep): ...
def pytest_addoption(parser) -> None: ...
def pytest_load_initial_conftests(early_config, parser, args) -> None: ...
def pytest_runtest_protocol(item): ...
def forked_run_report(item): ...
def report_process_crash(item, result): ...
