from _typeshed import Incomplete

DEFAULT_CERTFILE: Incomplete

class InvalidCertificateError(Exception): ...

def get_env_dict(use_TLS: bool = ...): ...
def get_scope(): ...
def validate_cert_file(cert_file) -> None: ...
def get_socket(desired_port: int = ...): ...
def pretty_logger(heading, msg) -> None: ...
def arg_validator_excepthook(exc_type, exc_value, exc_traceback) -> None: ...
def arg_validator(
    func_locals,
    valid_var_dict,
    valid_var_overwrite: Incomplete | None = ...,
    implementation_func_name: str = ...,
    strict_type_check: bool = ...,
    dev_mode: bool = ...,
) -> None: ...
